using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;
using System.Data;
using System.Data.OleDb;
using System.Data.Common;
using System.IO;
using YNetLib_45;

namespace DD2015_45.Forms.dax
{
  public partial class dx_daset_mdd : FormBase
  {
    string st_object_func = "UNdaset";
    string s34 = "" + (char)34;
    string s1310 = "" + (char)13 + (char)10;
    protected void Page_Load(object sender, EventArgs e)
    {
      li_Msg.Text = "";
      li_AccMsg.Text = "";
      //檢查權限&狀態
      if (sFN.checkAccessFunc(UserGkey, st_object_func, 09, UserLoginGkey, ref li_AccMsg))
      {
        if (!IsPostBack)
        {
          tx_mtable.Text = DAC.GetStringValue(Session["fmDASET_tx_DASET_DAAPX"]);
          tx_mtable.ReadOnly = true;
          tx_dtable1.Text = tx_mtable.Text.Substring(0, tx_mtable.Text.Length - 1) + "b1";
          tx_dtable2.Text = tx_mtable.Text.Substring(0, tx_mtable.Text.Length - 1) + "b2";
        }
      }

    }

    protected void bt_SERQ_Click(object sender, EventArgs e)
    {
      Response.Redirect("dx_daset.aspx");
    }

    protected void bt_SUR_Click(object sender, EventArgs e)
    {
      act_HTML();
    }

    protected void act_HTML()
    {
      string v_Str_YNET = "";
      string vOROW = "";
      string j_Tbl = "";
      string v_Tbl = DAC.GetStringValue(Session["fmDASET_tx_DASET_DATBL"]);
      string v_Apx = DAC.GetStringValue(Session["fmDASET_tx_DASET_DAAPX"]);
      //
      StreamWriter Fhdsw;
      string v_doc_file = "";
      string v_doc_http = "";
      string v_doc_guid = sFN.Get_guid5();
      //
      v_doc_file = sys_DocFilePath + tx_mtable.Text + "_mdd_HTML_" + v_doc_guid + ".txt";
      v_doc_http = tx_mtable.Text + "_mdd_HTML_" + v_doc_guid + ".txt";
      Fhdsw = File.CreateText(v_doc_file);
      v_Str_YNET = "";
      //
      v_Str_YNET += "<%@ Page Title=" + s34 + s34 + " Language=" + s34 + "C#" + s34 + " MasterPageFile=" + s34 + "~/SiteMM.Master" + s34 + " AutoEventWireup=" + s34 + "true" + s34 + " CodeBehind=" + s34 + "fm_temp_mdd.aspx.cs" + s34 + " Inherits=" + s34 + "DD2015_45.Forms.rix.fm_temp_mdd" + s34 + " %>" + s1310;
      v_Str_YNET += "<%@ Register Assembly=" + s34 + "Infragistics45.Web.v14.2, Version=14.2.20142.2146, Culture=neutral, PublicKeyToken=7dd5c3163f2cd0cb" + s34 + " Namespace=" + s34 + "Infragistics.Web.UI.ListControls" + s34 + " TagPrefix=" + s34 + "ig" + s34 + " %>" + s1310;
      v_Str_YNET += "<%@ Register Assembly=" + s34 + "Infragistics45.Web.v14.2, Version=14.2.20142.2146, Culture=neutral, PublicKeyToken=7dd5c3163f2cd0cb" + s34 + " Namespace=" + s34 + "Infragistics.Web.UI.LayoutControls" + s34 + " TagPrefix=" + s34 + "ig" + s34 + " %>" + s1310;
      v_Str_YNET += "<%@ Register Assembly=" + s34 + "Infragistics45.Web.v14.2, Version=14.2.20142.2146, Culture=neutral, PublicKeyToken=7dd5c3163f2cd0cb" + s34 + " Namespace=" + s34 + "Infragistics.Web.UI.GridControls" + s34 + " TagPrefix=" + s34 + "ig" + s34 + " %>" + s1310;
      v_Str_YNET += "<%@ Register Assembly=" + s34 + "Infragistics45.Web.v14.2, Version=14.2.20142.2146, Culture=neutral, PublicKeyToken=7dd5c3163f2cd0cb" + s34 + " Namespace=" + s34 + "Infragistics.Web.UI.EditorControls" + s34 + " TagPrefix=" + s34 + "ig" + s34 + " %>" + s1310;
      v_Str_YNET += "<%@ Register Assembly=" + s34 + "Infragistics45.WebUI.WebDataInput.v14.2, Version=14.2.20142.2146, Culture=neutral, PublicKeyToken=7dd5c3163f2cd0cb" + s34 + " Namespace=" + s34 + "Infragistics.WebUI.WebDataInput" + s34 + " TagPrefix=" + s34 + "igtxt" + s34 + " %>" + s1310;
      v_Str_YNET += "<%@ Register Assembly=" + s34 + "Infragistics45.WebUI.WebHtmlEditor.v14.2, Version=14.2.20142.2146, Culture=neutral, PublicKeyToken=7dd5c3163f2cd0cb" + s34 + " Namespace=" + s34 + "Infragistics.WebUI.WebHtmlEditor" + s34 + " TagPrefix=" + s34 + "ighedit" + s34 + " %>" + s1310;
      v_Str_YNET += "    " + s1310;
      v_Str_YNET += "<asp:Content ID=" + s34 + "Content1" + s34 + " ContentPlaceHolderID=" + s34 + "head" + s34 + " runat=" + s34 + "server" + s34 + ">" + s1310;
      v_Str_YNET += "  <style type=" + s34 + "text/css" + s34 + ">" + s1310;
      v_Str_YNET += "    .hide" + s1310;
      v_Str_YNET += "    {" + s1310;
      v_Str_YNET += "      visibility: hidden;" + s1310;
      v_Str_YNET += "    }" + s1310;
      v_Str_YNET += "    " + s1310;
      v_Str_YNET += "    .tdtop" + s1310;
      v_Str_YNET += "    {" + s1310;
      v_Str_YNET += "      vertical-align: top;" + s1310;
      v_Str_YNET += "    }" + s1310;
      v_Str_YNET += "    " + s1310;
      v_Str_YNET += "    .txRightWdg" + s1310;
      v_Str_YNET += "    {" + s1310;
      v_Str_YNET += "      text-align: right !important;" + s1310;
      v_Str_YNET += "    }" + s1310;
      v_Str_YNET += "  </style>" + s1310;
      v_Str_YNET += "</asp:Content>" + s1310;
      v_Str_YNET += "<asp:Content ID=" + s34 + "Content2" + s34 + " ContentPlaceHolderID=" + s34 + "ContentPlaceHolder1" + s34 + " runat=" + s34 + "server" + s34 + ">" + s1310;
      v_Str_YNET += "  <asp:UpdatePanel ID=" + s34 + "UpdatePanelForm" + s34 + " UpdateMode=" + s34 + "Conditional" + s34 + " runat=" + s34 + "server" + s34 + ">" + s1310;
      v_Str_YNET += "    <ContentTemplate>" + s1310;
      v_Str_YNET += "      <asp:Literal ID=" + s34 + "li_AccMsg" + s34 + " runat=" + s34 + "server" + s34 + "></asp:Literal>" + s1310;
      v_Str_YNET += "      <input id=" + s34 + "hh_GridGkey" + s34 + " type=" + s34 + "hidden" + s34 + " name=" + s34 + "hh_GridGkey" + s34 + " runat=" + s34 + "server" + s34 + " />" + s1310;
      v_Str_YNET += "      <input id=" + s34 + "hh_GridCtrl" + s34 + " type=" + s34 + "hidden" + s34 + " name=" + s34 + "hh_GridCtrl" + s34 + " runat=" + s34 + "server" + s34 + " />" + s1310;
      v_Str_YNET += "      <input id=" + s34 + "hh_ActKey" + s34 + " type=" + s34 + "hidden" + s34 + " name=" + s34 + "hh_ActGuidKey" + s34 + " runat=" + s34 + "server" + s34 + " />" + s1310;
      v_Str_YNET += "      <input id=" + s34 + "hh_mkey" + s34 + " type=" + s34 + "hidden" + s34 + " name=" + s34 + "hh_mkey" + s34 + " runat=" + s34 + "server" + s34 + " />" + s1310;
      v_Str_YNET += "      <input id=" + s34 + "hh_fun_name" + s34 + " type=" + s34 + "hidden" + s34 + " name=" + s34 + "hh_fun_name" + s34 + " runat=" + s34 + "server" + s34 + " />" + s1310;
      v_Str_YNET += "      <input id=" + s34 + "hh_fun_mkey" + s34 + " type=" + s34 + "hidden" + s34 + " name=" + s34 + "hh_fun_mkey" + s34 + " runat=" + s34 + "server" + s34 + " />" + s1310;
      v_Str_YNET += "      <input id=" + s34 + "hh_fun_mkey_old" + s34 + " type=" + s34 + "hidden" + s34 + " name=" + s34 + "hh_fun_mkey_old" + s34 + " runat=" + s34 + "server" + s34 + " />" + s1310;
      v_Str_YNET += "      <input id=" + s34 + "di_Window_Command" + s34 + " type=" + s34 + "hidden" + s34 + " name=" + s34 + "di_Window_Command" + s34 + " runat=" + s34 + "server" + s34 + " />" + s1310;
      v_Str_YNET += "      <input id=" + s34 + "hh_dtable1_OldNum_Field" + s34 + " type=" + s34 + "hidden" + s34 + " name=" + s34 + "hh_dtable1_OldNum_Field" + s34 + " runat=" + s34 + "server" + s34 + " />" + s1310;
      v_Str_YNET += "      <asp:Button ID=" + s34 + "btnAction" + s34 + " runat=" + s34 + "server" + s34 + " UseSubmitBehavior=" + s34 + "False" + s34 + " Visible=" + s34 + "false" + s34 + " />" + s1310;
      v_Str_YNET += "      <asp:Button ID=" + s34 + "btnPost" + s34 + " runat=" + s34 + "server" + s34 + " UseSubmitBehavior=" + s34 + "False" + s34 + " Visible=" + s34 + "false" + s34 + " />" + s1310;
      v_Str_YNET += "      <asp:Panel ID=" + s34 + "PanBtns" + s34 + " runat=" + s34 + "server" + s34 + " Width=" + s34 + "1000px" + s34 + ">" + s1310;
      v_Str_YNET += "        <table>" + s1310;
      v_Str_YNET += "          <tr>" + s1310;
      v_Str_YNET += "            <td>" + s1310;
      v_Str_YNET += "               <igtxt:WebImageButton ID=" + s34 + "bt_CAN" + s34 + " AccessKey=" + s34 + "C" + s34 + " runat=" + s34 + "server" + s34 + " UseBrowserDefaults=" + s34 + "False" + s34 + s1310;
      v_Str_YNET += "                 Height=" + s34 + "90%" + s34 + " Text=" + s34 + "C取消" + s34 + " ImageDirectory=" + s34 + "../../images/" + s34 + " OnClick=" + s34 + "bt_CAN_Click" + s34 + ">" + s1310;
      v_Str_YNET += "                 <Appearance>" + s1310;
      v_Str_YNET += "                   <Image Url=" + s34 + "form_cancel.png" + s34 + "></Image>" + s1310;
      v_Str_YNET += "                   <ButtonStyle Font-Names=" + s34 + "verdana" + s34 + " Font-Size=" + s34 + "12pt" + s34 + " />" + s1310;
      v_Str_YNET += "                 </Appearance>" + s1310;
      v_Str_YNET += "               </igtxt:WebImageButton>" + s1310;
      v_Str_YNET += "             </td>" + s1310;
      v_Str_YNET += "             <td>" + s1310;
      v_Str_YNET += "              <igtxt:WebImageButton ID=" + s34 + "bt_SAV" + s34 + " AccessKey=" + s34 + "S" + s34 + " runat=" + s34 + "server" + s34 + " UseBrowserDefaults=" + s34 + "False" + s34 + s1310;
      v_Str_YNET += "                Height=" + s34 + "90%" + s34 + " Text=" + s34 + "S存檔" + s34 + " ImageDirectory=" + s34 + "../../images/" + s34 + " OnClick=" + s34 + "bt_SAV_Click" + s34 + ">" + s1310;
      v_Str_YNET += "                <Appearance>" + s1310;
      v_Str_YNET += "                  <Image Url=" + s34 + "form_save.png" + s34 + "></Image>" + s1310;
      v_Str_YNET += "                  <ButtonStyle Font-Names=" + s34 + "verdana" + s34 + " Font-Size=" + s34 + "12pt" + s34 + " />" + s1310;
      v_Str_YNET += "                </Appearance>" + s1310;
      v_Str_YNET += "              </igtxt:WebImageButton>" + s1310;
      v_Str_YNET += "            </td>" + s1310;
      v_Str_YNET += "            <td>" + s1310;
      v_Str_YNET += "              <igtxt:WebImageButton ID=" + s34 + "bt_02" + s34 + " AccessKey=" + s34 + "N" + s34 + " runat=" + s34 + "server" + s34 + " UseBrowserDefaults=" + s34 + "False" + s34 + s1310;
      v_Str_YNET += "                Height=" + s34 + "90%" + s34 + " Text=" + s34 + "N新增" + s34 + " ImageDirectory=" + s34 + "../../images/" + s34 + " OnClick=" + s34 + "bt_02_Click" + s34 + ">" + s1310;
      v_Str_YNET += "                <Appearance>" + s1310;
      v_Str_YNET += "                  <Image Url=" + s34 + "form_new.png" + s34 + "></Image>" + s1310;
      v_Str_YNET += "                  <ButtonStyle Font-Names=" + s34 + "verdana" + s34 + " Font-Size=" + s34 + "12pt" + s34 + " />" + s1310;
      v_Str_YNET += "                </Appearance>" + s1310;
      v_Str_YNET += "              </igtxt:WebImageButton>" + s1310;
      v_Str_YNET += "            </td>" + s1310;
      v_Str_YNET += "            <td>" + s1310;
      v_Str_YNET += "              <igtxt:WebImageButton ID=" + s34 + "bt_03" + s34 + " AccessKey=" + s34 + "I" + s34 + " runat=" + s34 + "server" + s34 + " UseBrowserDefaults=" + s34 + "False" + s34 + s1310;
      v_Str_YNET += "                Height=" + s34 + "90%" + s34 + " Text=" + s34 + "I插入" + s34 + " ImageDirectory=" + s34 + "../../images/" + s34 + ">" + s1310;
      v_Str_YNET += "                <Appearance>" + s1310;
      v_Str_YNET += "                  <Image Url=" + s34 + "form_new.png" + s34 + "></Image>" + s1310;
      v_Str_YNET += "                  <ButtonStyle Font-Names=" + s34 + "verdana" + s34 + " Font-Size=" + s34 + "12pt" + s34 + " />" + s1310;
      v_Str_YNET += "                </Appearance>" + s1310;
      v_Str_YNET += "              </igtxt:WebImageButton>" + s1310;
      v_Str_YNET += "            </td>" + s1310;
      v_Str_YNET += "            <td>" + s1310;
      v_Str_YNET += "              <igtxt:WebImageButton ID=" + s34 + "bt_04" + s34 + " AccessKey=" + s34 + "M" + s34 + " runat=" + s34 + "server" + s34 + " UseBrowserDefaults=" + s34 + "False" + s34 + s1310;
      v_Str_YNET += "                Height=" + s34 + "90%" + s34 + " Text=" + s34 + "M更正" + s34 + " ImageDirectory=" + s34 + "../../images/" + s34 + " OnClick=" + s34 + "bt_04_Click" + s34 + ">" + s1310;
      v_Str_YNET += "                <Appearance>" + s1310;
      v_Str_YNET += "                  <Image Url=" + s34 + "form_edit.png" + s34 + "></Image>" + s1310;
      v_Str_YNET += "                  <ButtonStyle Font-Names=" + s34 + "verdana" + s34 + " Font-Size=" + s34 + "12pt" + s34 + " />" + s1310;
      v_Str_YNET += "                </Appearance>" + s1310;
      v_Str_YNET += "              </igtxt:WebImageButton>" + s1310;
      v_Str_YNET += "            </td>" + s1310;
      v_Str_YNET += "            <td>" + s1310;
      v_Str_YNET += "              <igtxt:WebImageButton ID=" + s34 + "bt_05" + s34 + " AccessKey=" + s34 + "X" + s34 + " runat=" + s34 + "server" + s34 + " AutoSubmit=" + s34 + "false" + s34 + " UseBrowserDefaults=" + s34 + "False" + s34 + s1310;
      v_Str_YNET += "                Height=" + s34 + "90%" + s34 + " Text=" + s34 + "X刪除" + s34 + " ImageDirectory=" + s34 + "../../images/" + s34 + " OnClick=" + s34 + "bt_05_Click" + s34 + ">" + s1310;
      v_Str_YNET += "                <Appearance>" + s1310;
      v_Str_YNET += "                  <Image Url=" + s34 + "form_delete.png" + s34 + "></Image>" + s1310;
      v_Str_YNET += "                  <ButtonStyle Font-Names=" + s34 + "verdana" + s34 + " Font-Size=" + s34 + "12pt" + s34 + " />" + s1310;
      v_Str_YNET += "                </Appearance>" + s1310;
      v_Str_YNET += "              </igtxt:WebImageButton>" + s1310;
      v_Str_YNET += "            </td>" + s1310;
      v_Str_YNET += "            <td>" + s1310;
      v_Str_YNET += "              <igtxt:WebImageButton ID=" + s34 + "bt_06" + s34 + " AccessKey=" + s34 + "O" + s34 + " runat=" + s34 + "server" + s34 + " UseBrowserDefaults=" + s34 + "False" + s34 + s1310;
      v_Str_YNET += "                Height=" + s34 + "90%" + s34 + " Text=" + s34 + "O複製" + s34 + " ImageDirectory=" + s34 + "../../images/" + s34 + ">" + s1310;
      v_Str_YNET += "                <Appearance>" + s1310;
      v_Str_YNET += "                  <Image Url=" + s34 + "form_copy.png" + s34 + "></Image>" + s1310;
      v_Str_YNET += "                  <ButtonStyle Font-Names=" + s34 + "verdana" + s34 + " Font-Size=" + s34 + "12pt" + s34 + " />" + s1310;
      v_Str_YNET += "                </Appearance>" + s1310;
      v_Str_YNET += "              </igtxt:WebImageButton>" + s1310;
      v_Str_YNET += "            </td>" + s1310;
      v_Str_YNET += "            <td>" + s1310;
      v_Str_YNET += "              <igtxt:WebImageButton ID=" + s34 + "bt_07" + s34 + " AccessKey=" + s34 + "P" + s34 + " runat=" + s34 + "server" + s34 + " UseBrowserDefaults=" + s34 + "False" + s34 + s1310;
      v_Str_YNET += "                Height=" + s34 + "90%" + s34 + " Text=" + s34 + "P列印" + s34 + " ImageDirectory=" + s34 + "../../images/" + s34 + ">" + s1310;
      v_Str_YNET += "                <Appearance>" + s1310;
      v_Str_YNET += "                  <Image Url=" + s34 + "form_print.png" + s34 + "></Image>" + s1310;
      v_Str_YNET += "                  <ButtonStyle Font-Names=" + s34 + "verdana" + s34 + " Font-Size=" + s34 + "12pt" + s34 + " />" + s1310;
      v_Str_YNET += "                </Appearance>" + s1310;
      v_Str_YNET += "              </igtxt:WebImageButton>" + s1310;
      v_Str_YNET += "            </td>" + s1310;
      v_Str_YNET += "            <td>" + s1310;
      v_Str_YNET += "              <igtxt:WebImageButton ID=" + s34 + "bt_08" + s34 + " AccessKey=" + s34 + "F" + s34 + " runat=" + s34 + "server" + s34 + " UseBrowserDefaults=" + s34 + "False" + s34 + s1310;
      v_Str_YNET += "                Height=" + s34 + "90%" + s34 + " Text=" + s34 + "F查詢" + s34 + " ImageDirectory=" + s34 + "../../images/" + s34 + " OnClick=" + s34 + "bt_08_Click" + s34 + ">" + s1310;
      v_Str_YNET += "                <Appearance>" + s1310;
      v_Str_YNET += "                  <Image Url=" + s34 + "form_serch.png" + s34 + "></Image>" + s1310;
      v_Str_YNET += "                  <ButtonStyle Font-Names=" + s34 + "verdana" + s34 + " Font-Size=" + s34 + "12pt" + s34 + " />" + s1310;
      v_Str_YNET += "                </Appearance>" + s1310;
      v_Str_YNET += "              </igtxt:WebImageButton>" + s1310;
      v_Str_YNET += "            </td>" + s1310;
      v_Str_YNET += "            <td>" + s1310;
      v_Str_YNET += "              <igtxt:WebImageButton ID=" + s34 + "bt_09" + s34 + " AccessKey=" + s34 + "T" + s34 + " runat=" + s34 + "server" + s34 + " UseBrowserDefaults=" + s34 + "False" + s34 + s1310;
      v_Str_YNET += "                Height=" + s34 + "90%" + s34 + " Text=" + s34 + "T轉單" + s34 + " ImageDirectory=" + s34 + "../../images/" + s34 + ">" + s1310;
      v_Str_YNET += "                <Appearance>" + s1310;
      v_Str_YNET += "                  <Image Url=" + s34 + "form_copy.png" + s34 + "></Image>" + s1310;
      v_Str_YNET += "                  <ButtonStyle Font-Names=" + s34 + "verdana" + s34 + " Font-Size=" + s34 + "12pt" + s34 + " />" + s1310;
      v_Str_YNET += "                </Appearance>" + s1310;
      v_Str_YNET += "              </igtxt:WebImageButton>" + s1310;
      v_Str_YNET += "            </td>" + s1310;
      v_Str_YNET += "            <td>" + s1310;
      v_Str_YNET += "              <igtxt:WebImageButton ID=" + s34 + "bt_10" + s34 + " AccessKey=" + s34 + "E" + s34 + " runat=" + s34 + "server" + s34 + " UseBrowserDefaults=" + s34 + "False" + s34 + s1310;
      v_Str_YNET += "                Height=" + s34 + "90%" + s34 + " Text=" + s34 + "Excel" + s34 + " ImageDirectory=" + s34 + "../../images/" + s34 + ">" + s1310;
      v_Str_YNET += "                <Appearance>" + s1310;
      v_Str_YNET += "                  <Image Url=" + s34 + "form_excel.png" + s34 + "></Image>" + s1310;
      v_Str_YNET += "                  <ButtonStyle Font-Names=" + s34 + "verdana" + s34 + " Font-Size=" + s34 + "12pt" + s34 + " />" + s1310;
      v_Str_YNET += "                </Appearance>" + s1310;
      v_Str_YNET += "              </igtxt:WebImageButton>" + s1310;
      v_Str_YNET += "            </td>" + s1310;
      v_Str_YNET += "            <td>" + s1310;
      v_Str_YNET += "              <igtxt:WebImageButton ID=" + s34 + "bt_11" + s34 + " runat=" + s34 + "server" + s34 + " UseBrowserDefaults=" + s34 + "False" + s34 + s1310;
      v_Str_YNET += "                Height=" + s34 + "90%" + s34 + " Text=" + s34 + "功能" + s34 + " ImageDirectory=" + s34 + "../../images/" + s34 + ">" + s1310;
      v_Str_YNET += "                <Appearance>" + s1310;
      v_Str_YNET += "                  <Image Url=" + s34 + "form_edit.png" + s34 + "></Image>" + s1310;
      v_Str_YNET += "                  <ButtonStyle Font-Names=" + s34 + "verdana" + s34 + " Font-Size=" + s34 + "12pt" + s34 + " />" + s1310;
      v_Str_YNET += "                </Appearance>" + s1310;
      v_Str_YNET += "              </igtxt:WebImageButton>" + s1310;
      v_Str_YNET += "            </td>" + s1310;
      v_Str_YNET += "            <td>" + s1310;
      v_Str_YNET += "              <igtxt:WebImageButton ID=" + s34 + "bt_QUT" + s34 + " AccessKey=" + s34 + "Q" + s34 + " runat=" + s34 + "server" + s34 + " UseBrowserDefaults=" + s34 + "False" + s34 + s1310;
      v_Str_YNET += "                Height=" + s34 + "90%" + s34 + " Text=" + s34 + "Q離開" + s34 + " ImageDirectory=" + s34 + "../../images/" + s34 + " OnClick=" + s34 + "bt_QUT_Click" + s34 + ">" + s1310;
      v_Str_YNET += "                <Appearance>" + s1310;
      v_Str_YNET += "                  <Image Url=" + s34 + "form_quit.png" + s34 + "></Image>" + s1310;
      v_Str_YNET += "                  <ButtonStyle Font-Names=" + s34 + "verdana" + s34 + " Font-Size=" + s34 + "12pt" + s34 + " />" + s1310;
      v_Str_YNET += "                </Appearance>" + s1310;
      v_Str_YNET += "              </igtxt:WebImageButton>" + s1310;
      v_Str_YNET += "            </td>" + s1310;
      v_Str_YNET += "          </tr>" + s1310;
      v_Str_YNET += "        </table>" + s1310;
      v_Str_YNET += "        <table>" + s1310;
      v_Str_YNET += "          <tr>" + s1310;
      v_Str_YNET += "            <td>" + s1310;
      v_Str_YNET += "              <asp:Label ID=" + s34 + "lb_ErrorMessage" + s34 + " runat=" + s34 + "server" + s34 + " Text=" + s34 + s34 + " EnableViewState=" + s34 + "false" + s34 + " Visible=" + s34 + "false" + s34 + " CssClass=" + s34 + "ErrorMessage" + s34 + "></asp:Label>" + s1310;
      v_Str_YNET += "            </td>" + s1310;
      v_Str_YNET += "          </tr>" + s1310;
      v_Str_YNET += "        </table>" + s1310;
      v_Str_YNET += "      </asp:Panel>"+ s1310;
      v_Str_YNET += "      <ig:WebTab ID=" + s34 + "WebTab_form" + s34 + " runat=" + s34 + "server" + s34 + " Width=" + s34 + "1200px" + s34 + " StyleSetName=" + s34 + "Claymation" + s34 + " StyleSetPath=" + s34 + "~/ig_res" + s34 + " TabItemSize=" + s34 + "100px" + s34 + " SelectedIndex=" + s34 + "1" + s34 + ">"+ s1310;
      v_Str_YNET += "        <Tabs>"+ s1310;
      v_Str_YNET += "          <ig:ContentTabItem runat=" + s34 + "server" + s34 + " Text=" + s34 + "查詢" + s34 + ">"+ s1310;
      v_Str_YNET += "            <Template>"+ s1310;
      v_Str_YNET += "              <asp:Panel ID=" + s34 + "PanSer" + s34 + " runat=" + s34 + "server" + s34 + " Width=" + s34 + "1000px" + s34 + ">"+ s1310;
      v_Str_YNET += "                <table>"+ s1310;
      v_Str_YNET += "                  <tr>"+ s1310;
      v_Str_YNET += "                    <td>"+ s1310;
      v_Str_YNET += "                      <ig:WebTab ID=" + s34 + "WebTab_SER" + s34 + " runat=" + s34 + "server" + s34 + " Width=" + s34 + "1100px" + s34 + " StyleSetName=" + s34 + "Pear" + s34 + " StyleSetPath=" + s34 + "~/ig_res" + s34 + " TabItemSize=" + s34 + "70px" + s34 + ">"+ s1310;
      v_Str_YNET += "                        <Tabs>"+ s1310;
      v_Str_YNET += "                          <ig:ContentTabItem runat=" + s34 + "server" + s34 + " Text=" + s34 + "一般" + s34 + ">"+ s1310;
      v_Str_YNET += "                            <Template>"+ s1310;
      v_Str_YNET += "                              <asp:Panel ID=" + s34 + "PanSerComm" + s34 + " runat=" + s34 + "server" + s34 + " Width=" + s34 + "1000px" + s34 + ">"+ s1310;
      v_Str_YNET += "                                <table>"+ s1310;
      v_Str_YNET += "                                  <tr>"+ s1310;
      v_Str_YNET += "                                    <td>&nbsp;"+ s1310;
      v_Str_YNET += "                                    </td>"+ s1310;
      v_Str_YNET += "                                  </tr>"+ s1310;
      v_Str_YNET += "                                  <tr>"+ s1310;
      v_Str_YNET += "                                    <td>"+ s1310;
      v_Str_YNET += "                                      <table>"+ s1310;
      v_Str_YNET += "                                        <tr>"+ s1310;
      v_Str_YNET += "                                          <td>"+ s1310;
      v_Str_YNET += "                                            <asp:Label ID=" + s34 + "lb_mtable_BDDTS_s1" + s34 + " runat=" + s34 + "server" + s34 + " Text=" + s34 + "開始日期" + s34 + "></asp:Label>"+ s1310;
      v_Str_YNET += "                                          </td>"+ s1310;
      v_Str_YNET += "                                          <td>"+ s1310;
      v_Str_YNET += "                                            <ig:WebDatePicker ID=" + s34 + "tx_mtable_BDDTS_s1" + s34 + " Width=" + s34 + "100px" + s34 + " CssClass=" + s34 + "Office2010Blue" + s34 + " runat=" + s34 + "server" + s34 + "></ig:WebDatePicker>"+ s1310;
      v_Str_YNET += "                                          </td>"+ s1310;
      v_Str_YNET += "                                          <td>"+ s1310;
      v_Str_YNET += "                                            <asp:Label ID=" + s34 + "lb_mtable_BDDTS_s2" + s34 + " runat=" + s34 + "server" + s34 + " Text=" + s34 + "～" + s34 + "></asp:Label>"+ s1310;
      v_Str_YNET += "                                          </td>"+ s1310;
      v_Str_YNET += "                                          <td>"+ s1310;
      v_Str_YNET += "                                            <ig:WebDatePicker ID=" + s34 + "tx_mtable_BDDTS_s2" + s34 + " Width=" + s34 + "100px" + s34 + " CssClass=" + s34 + "Office2010Blue" + s34 + " runat=" + s34 + "server" + s34 + "></ig:WebDatePicker>"+ s1310;
      v_Str_YNET += "                                          </td>"+ s1310;
      v_Str_YNET += "                                        </tr>"+ s1310;
      v_Str_YNET += "                                      </table>"+ s1310;
      v_Str_YNET += "                                    </td>"+ s1310;
      v_Str_YNET += "                                  </tr>"+ s1310;
      v_Str_YNET += "                                  <tr>"+ s1310;
      v_Str_YNET += "                                    <td>"+ s1310;
      v_Str_YNET += "                                      <asp:Label ID=" + s34 + "lb_mtable_BDPTN" + s34 + " runat=" + s34 + "server" + s34 + " Text=" + s34 + "商品編號" + s34 + "></asp:Label>"+ s1310;
      v_Str_YNET += "                                      <asp:TextBox ID=" + s34 + "tx_mtable_BDPTN_s" + s34 + " Width=" + s34 + "80px" + s34 + " runat=" + s34 + "server" + s34 + " MaxLength=" + s34 + "30" + s34 + "></asp:TextBox>"+ s1310;
      v_Str_YNET += "                                      <asp:TextBox ID=" + s34 + "tx_bpud_BPTNA_s" + s34 + " Width=" + s34 + "80px" + s34 + " runat=" + s34 + "server" + s34 + " MaxLength=" + s34 + "30" + s34 + " ReadOnly=" + s34 + "true" + s34 + "></asp:TextBox>"+ s1310;
      v_Str_YNET += "                                    </td>"+ s1310;
      v_Str_YNET += "                                  </tr>"+ s1310;
      v_Str_YNET += "                                  <tr>"+ s1310;
      v_Str_YNET += "                                    <td>&nbsp;</td>"+ s1310;
      v_Str_YNET += "                                  </tr>"+ s1310;
      v_Str_YNET += "                                </table>"+ s1310;
      v_Str_YNET += "                              </asp:Panel>"+ s1310;
      v_Str_YNET += "                            </Template>"+ s1310;
      v_Str_YNET += "                          </ig:ContentTabItem>"+ s1310;
      v_Str_YNET += "                          <ig:ContentTabItem runat=" + s34 + "server" + s34 + " Text=" + s34 + "進階" + s34 + ">"+ s1310;
      v_Str_YNET += "                            <Template>"+ s1310;
      v_Str_YNET += "                              <asp:Panel ID=" + s34 + "PanSerAdv" + s34 + " runat=" + s34 + "server" + s34 + " Width=" + s34 + "1000px" + s34 + ">"+ s1310;
      v_Str_YNET += "                                <table>"+ s1310;
      v_Str_YNET += "                                  <tr>"+ s1310;
      v_Str_YNET += "                                    <td></td>"+ s1310;
      v_Str_YNET += "                                  </tr>"+ s1310;
      v_Str_YNET += "                                </table>"+ s1310;
      v_Str_YNET += "                              </asp:Panel>"+ s1310;
      v_Str_YNET += "                            </Template>"+ s1310;
      v_Str_YNET += "                          </ig:ContentTabItem>"+ s1310;
      v_Str_YNET += "                        </Tabs>"+ s1310;
      v_Str_YNET += "                      </ig:WebTab>"+ s1310;
      v_Str_YNET += "                  </tr>"+ s1310;
      v_Str_YNET += "                </table>"+ s1310;
      v_Str_YNET += "              </asp:Panel>" + s1310;

      v_Str_YNET += "              <asp:Panel ID=" + s34 + "PanGridA" + s34 + " runat=" + s34 + "server" + s34 + " Width=" + s34 + "1000px" + s34 + ">" + s1310;
      v_Str_YNET += "                <ig:WebDataGrid ID=" + s34 + "WebDataGrid_mtable" + s34 + " runat=" + s34 + "server" + s34   + s1310;
      v_Str_YNET += "                  EnableAjax=" + s34 + "false" + s34 + " EnableViewState=" + s34 + "True" + s34 + " EnableDataViewState=" + s34 + "True" + s34   + s1310;
      v_Str_YNET += "                  Width=" + s34 + "1100px" + s34 + " AutoGenerateColumns=" + s34 + "False" + s34 + " DataKeyFields=" + s34 + "mtable_gkey" + s34 + " OnRowSelectionChanged=" + s34 + "WebDataGrid_mtable_RowSelectionChanged" + s34 + ">" + s1310;
      v_Str_YNET += "                  <Columns>" + s1310;
      v_Str_YNET += "                    <ig:BoundDataField DataFieldName=" + s34 + "mtable_BDCCN" + s34 + " Key=" + s34 + "mtable_BDCCN" + s34 + " Width=" + s34 + "100px" + s34 + ">" + s1310;
      v_Str_YNET += "                      <Header Text=" + s34 + "mtable_BDCCN" + s34 + ">" + s1310;
      v_Str_YNET += "                      </Header>" + s1310;
      v_Str_YNET += "                    </ig:BoundDataField>" + s1310;
      v_Str_YNET += "                    <ig:BoundDataField DataFieldName=" + s34 + "mtable_BDDTS" + s34 + " Key=" + s34 + "mtable_BDDTS" + s34 + " Width=" + s34 + "100px" + s34 + ">" + s1310;
      v_Str_YNET += "                      <Header Text=" + s34 + "mtable_BDDTS" + s34 + ">" + s1310;
      v_Str_YNET += "                      </Header>" + s1310;
      v_Str_YNET += "                    </ig:BoundDataField>" + s1310;
      v_Str_YNET += "                    <ig:BoundDataField DataFieldName=" + s34 + "mtable_BDPTN" + s34 + " Key=" + s34 + "mtable_BDPTN" + s34 + " Width=" + s34 + "120px" + s34 + ">" + s1310;
      v_Str_YNET += "                      <Header Text=" + s34 + "mtable_BDPTN" + s34 + ">" + s1310;
      v_Str_YNET += "                      </Header>" + s1310;
      v_Str_YNET += "                    </ig:BoundDataField>" + s1310;
      v_Str_YNET += "                    <ig:BoundDataField DataFieldName=" + s34 + "bpud_BPTNA" + s34 + " Key=" + s34 + "bpud_BPTNA" + s34 + " Width=" + s34 + "300px" + s34 + ">" + s1310;
      v_Str_YNET += "                      <Header Text=" + s34 + "bpud_BPTNA" + s34 + ">" + s1310;
      v_Str_YNET += "                      </Header>" + s1310;
      v_Str_YNET += "                    </ig:BoundDataField>" + s1310;
      v_Str_YNET += "                    <ig:BoundDataField DataFieldName=" + s34 + "mtable_BDNUM" + s34 + " Key=" + s34 + "mtable_BDNUM" + s34 + " Width=" + s34 + "100px" + s34 + ">" + s1310;
      v_Str_YNET += "                      <Header Text=" + s34 + "mtable_BDNUM" + s34 + ">" + s1310;
      v_Str_YNET += "                      </Header>" + s1310;
      v_Str_YNET += "                    </ig:BoundDataField>" + s1310;
      v_Str_YNET += "                    <ig:BoundDataField DataFieldName=" + s34 + "bdlr_BDNAM" + s34 + " Key=" + s34 + "bdlr_BDNAM" + s34 + " Width=" + s34 + "200px" + s34 + ">" + s34 + s1310;
      v_Str_YNET += "                      <Header Text=" + s34 + "bdlr_BDNAM" + s34 + ">" + s1310;
      v_Str_YNET += "                      </Header>" + s1310;
      v_Str_YNET += "                    </ig:BoundDataField>" + s1310;
      v_Str_YNET += "                    <ig:BoundDataField DataFieldName=" + s34 + "mtable_gkey" + s34 + " Key=" + s34 + "mtable_gkey" + s34 + " Hidden=" + s34 + "true" + s34 + " HtmlEncode=" + s34 + "true" + s34 + ">" + s1310;
      v_Str_YNET += "                      <Header Text=" + s34 + "mtable_gkey" + s34 + ">" + s1310;
      v_Str_YNET += "                      </Header>" + s1310;
      v_Str_YNET += "                    </ig:BoundDataField>" + s1310;
      v_Str_YNET += "                    <ig:BoundDataField DataFieldName=" + s34 + "mtable_mkey" + s34 + " Key=" + s34 + "mtable_mkey" + s34 + " Hidden=" + s34 + "true" + s34 + " HtmlEncode=" + s34 + "true" + s34 + ">" + s1310;
      v_Str_YNET += "                      <Header Text=" + s34 + "mtable_mkey" + s34 + ">" + s1310;
      v_Str_YNET += "                      </Header>" + s1310;
      v_Str_YNET += "                    </ig:BoundDataField>" + s1310;
      v_Str_YNET += "                  </Columns>" + s1310;
      v_Str_YNET += "                  <Behaviors>" + s1310;
      v_Str_YNET += "                    <ig:Selection CellClickAction=" + s34 + "Row" + s34 + " CellSelectType=" + s34 + "None" + s34 + " RowSelectType=" + s34 + "Single" + s34 + ">" + s1310;
      v_Str_YNET += "                      <AutoPostBackFlags RowSelectionChanged=" + s34 + "True" + s34 + " />" + s1310;
      v_Str_YNET += "                    </ig:Selection>" + s1310;
      v_Str_YNET += "                    <ig:RowSelectors>" + s1310;
      v_Str_YNET += "                    </ig:RowSelectors>" + s1310;
      v_Str_YNET += "                    <ig:Sorting SortingMode=" + s34 + "Multi" + s34 + ">" + s1310;
      v_Str_YNET += "                    </ig:Sorting>" + s1310;
      v_Str_YNET += "                    <ig:Paging PagerMode=" + s34 + "NumericFirstLast" + s34 + ">" + s1310;
      v_Str_YNET += "                    </ig:Paging>" + s1310;
      v_Str_YNET += "                  </Behaviors>" + s1310;
      v_Str_YNET += "                </ig:WebDataGrid>" + s1310;
      v_Str_YNET += "              </asp:Panel>" + s1310;
      v_Str_YNET += "            </Template>" + s1310;
      v_Str_YNET += "          </ig:ContentTabItem>" + s1310;
      v_Str_YNET += "          <ig:ContentTabItem runat=" + s34 + "server" + s34 + " Text=" + s34 + "編輯" + s34 + ">" + s1310;
      v_Str_YNET += "            <Template>" + s1310;
      v_Str_YNET += "              <table>" + s1310;
      v_Str_YNET += "                <tr>" + s1310;
      v_Str_YNET += "                <td class=" + s34 + "tdtop" + s34 + ">" + s1310;
      v_Str_YNET += "                    <asp:Panel ID=" + s34 + "PanEdtLeft" + s34 + " runat=" + s34 + "server" + s34 + " Width=" + s34 + "250px" + s34 + " BorderStyle=" + s34 + "Inset" + s34 + ">" + s1310;
      v_Str_YNET += "                      <ig:WebDataGrid ID=" + s34 + "WebDataGrid_mtable_ba" + s34 + " runat=" + s34 + "server" + s34   + s1310;
      v_Str_YNET += "                        EnableAjax=" + s34 + "False" + s34 + " EnableDataViewState=" + s34 + "True" + s34   + s1310;
      v_Str_YNET += "                        Width=" + s34 + "240px" + s34 + " AutoGenerateColumns=" + s34 + "False" + s34 + " DataKeyFields=" + s34 + "mtable_gkey" + s34 + " OnRowSelectionChanged=" + s34 + "WebDataGrid_mtable_ba_RowSelectionChanged" + s34 + ">" + s1310;
      v_Str_YNET += "                        <Columns>" + s1310;
      v_Str_YNET += "                          <ig:BoundDataField DataFieldName=" + s34 + "mtable_BDCCN" + s34 + " Key=" + s34 + "mtable_BDCCN" + s34 + " Width=" + s34 + "100px" + s34 + ">" + s1310;
      v_Str_YNET += "                            <Header Text=" + s34 + "mtable_BDCCN" + s34 + ">" + s1310;
      v_Str_YNET += "                            </Header>" + s1310;
      v_Str_YNET += "                          </ig:BoundDataField>" + s1310;
      v_Str_YNET += "                          <ig:BoundDataField DataFieldName=" + s34 + "mtable_BDDTS" + s34 + " Key=" + s34 + "mtable_BDDTS" + s34 + " Width=" + s34 + "100px" + s34 + ">" + s1310;
      v_Str_YNET += "                            <Header Text=" + s34 + "mtable_BDDTS" + s34 + ">" + s1310;
      v_Str_YNET += "                            </Header>" + s1310;
      v_Str_YNET += "                          </ig:BoundDataField>" + s1310;
      v_Str_YNET += "                          <ig:BoundDataField DataFieldName=" + s34 + "mtable_gkey" + s34 + " Key=" + s34 + "mtable_gkey" + s34 + " Hidden=" + s34 + "true" + s34 + " HtmlEncode=" + s34 + "true" + s34 + ">" + s1310;
      v_Str_YNET += "                            <Header Text=" + s34 + "mtable_gkey" + s34 + ">" + s1310;
      v_Str_YNET += "                            </Header>" + s1310;
      v_Str_YNET += "                          </ig:BoundDataField>" + s1310;
      v_Str_YNET += "                          <ig:BoundDataField DataFieldName=" + s34 + "mtable_mkey" + s34 + " Key=" + s34 + "mtable_mkey" + s34 + " Hidden=" + s34 + "true" + s34 + " HtmlEncode=" + s34 + "true" + s34 + ">" + s1310;
      v_Str_YNET += "                            <Header Text=" + s34 + "mtable_mkey" + s34 + ">" + s1310;
      v_Str_YNET += "                            </Header>" + s1310;
      v_Str_YNET += "                          </ig:BoundDataField>" + s1310;
      v_Str_YNET += "                        </Columns>" + s1310;
      v_Str_YNET += "                        <Behaviors>" + s1310;
      v_Str_YNET += "                          <ig:Selection CellClickAction=" + s34 + "Row" + s34 + " CellSelectType=" + s34 + "None" + s34 + " RowSelectType=" + s34 + "Single" + s34 + ">" + s1310;
      v_Str_YNET += "                            <AutoPostBackFlags RowSelectionChanged=" + s34 + "True" + s34 + " />" + s1310;
      v_Str_YNET += "                          </ig:Selection>" + s1310;
      v_Str_YNET += "                          <ig:RowSelectors>" + s1310;
      v_Str_YNET += "                          </ig:RowSelectors>" + s1310;
      v_Str_YNET += "                          <ig:Sorting>" + s1310;
      v_Str_YNET += "                          </ig:Sorting>" + s1310;
      v_Str_YNET += "                          <ig:Paging>" + s1310;
      v_Str_YNET += "                          </ig:Paging>" + s1310;
      v_Str_YNET += "                        </Behaviors>" + s1310;
      v_Str_YNET += "                      </ig:WebDataGrid>" + s1310;
      v_Str_YNET += "                    </asp:Panel>" + s1310;
      v_Str_YNET += "                  </td>" + s1310;
      v_Str_YNET += "                  <td>" + s1310;
      v_Str_YNET += "                    <asp:Panel ID=" + s34 + "PanEdtRightTop" + s34 + " runat=" + s34 + "server" + s34 + " Width=" + s34 + "800px" + s34 + " BorderStyle=" + s34 + "Inset" + s34 + ">" + s1310;

      v_Str_YNET += "                      <table>"+ s1310;
      v_Str_YNET += "                        <tr>"+ s1310;
      v_Str_YNET += "                          <td>&nbsp;"+ s1310;
      v_Str_YNET += "                          </td>"+ s1310;
      v_Str_YNET += "                        </tr>"+ s1310;
      v_Str_YNET += "                        <tr>"+ s1310;
      v_Str_YNET += "                          <td>"+ s1310;
      v_Str_YNET += "                            <asp:Label ID=" + s34 + "lb_mtable_BDCCN" + s34 + " runat=" + s34 + "server" + s34 + " Text=" + s34 + "合約編號" + s34 + "></asp:Label>"+ s1310;
      v_Str_YNET += "                            <asp:TextBox ID=" + s34 + "tx_mtable_BDCCN" + s34 + " Width=" + s34 + "120px" + s34 + " runat=" + s34 + "server" + s34 + " MaxLength=" + s34 + "30" + s34 + "></asp:TextBox>"+ s1310;
      v_Str_YNET += "                          </td>"+ s1310;
      v_Str_YNET += "                          <td>"+ s1310;
      v_Str_YNET += "                            <table>"+ s1310;
      v_Str_YNET += "                              <tr>"+ s1310;
      v_Str_YNET += "                                <td>"+ s1310;
      v_Str_YNET += "                                  <asp:Label ID=" + s34 + "lb_mtable_BDDTS" + s34 + " runat=" + s34 + "server" + s34 + " Text=" + s34 + "開始日期" + s34 + "></asp:Label>"+ s1310;
      v_Str_YNET += "                                </td>"+ s1310;
      v_Str_YNET += "                                <td>"+ s1310;
      v_Str_YNET += "                                  <ig:WebDatePicker ID=" + s34 + "tx_mtable_BDDTS" + s34 + " Width=" + s34 + "120px" + s34 + " runat=" + s34 + "server" + s34 + " DisplayModeFormat=" + s34 + "d" + s34 + " Font-Size=" + s34 + "Medium" + s34 + "></ig:WebDatePicker>"+ s1310;
      v_Str_YNET += "                                </td>"+ s1310;
      v_Str_YNET += "                              </tr>"+ s1310;
      v_Str_YNET += "                            </table>"+ s1310;
      v_Str_YNET += "                          </td>"+ s1310;
      v_Str_YNET += "                          <td>"+ s1310;
      v_Str_YNET += "                            <table>"+ s1310;
      v_Str_YNET += "                              <tr>"+ s1310;
      v_Str_YNET += "                                <td>"+ s1310;
      v_Str_YNET += "                                  <asp:Label ID=" + s34 + "lb_mtable_BDDTE" + s34 + " runat=" + s34 + "server" + s34 + " Text=" + s34 + "結束日期" + s34 + "></asp:Label>"+ s1310;
      v_Str_YNET += "                                </td>"+ s1310;
      v_Str_YNET += "                                <td>"+ s1310;
      v_Str_YNET += "                                  <ig:WebDatePicker ID=" + s34 + "tx_mtable_BDDTE" + s34 + " Width=" + s34 + "120px" + s34 + " runat=" + s34 + "server" + s34 + " DisplayModeFormat=" + s34 + "d" + s34 + " Font-Size=" + s34 + "Medium" + s34 + "></ig:WebDatePicker>"+ s1310;
      v_Str_YNET += "                                </td>"+ s1310;
      v_Str_YNET += "                              </tr>"+ s1310;
      v_Str_YNET += "                            </table>"+ s1310;
      v_Str_YNET += "                          </td>"+ s1310;
      v_Str_YNET += "                        </tr>"+ s1310;
      v_Str_YNET += "                        <tr>"+ s1310;
      v_Str_YNET += "                          <td colspan=" + s34 + "3" + s34 + ">"+ s1310;
      v_Str_YNET += "                            <asp:Label ID=" + s34 + "lb_mtable_BDNUM" + s34 + " runat=" + s34 + "server" + s34 + " Text=" + s34 + "出版社號" + s34 + "></asp:Label>"+ s1310;
      v_Str_YNET += "                            <asp:TextBox ID=" + s34 + "tx_mtable_BDNUM" + s34 + " Width=" + s34 + "120px" + s34 + " runat=" + s34 + "server" + s34 + " MaxLength=" + s34 + "10" + s34 + "></asp:TextBox>"+ s1310;
      v_Str_YNET += "                            <asp:TextBox ID=" + s34 + "tx_bdlr_BDNAM" + s34 + " Width=" + s34 + "360px" + s34 + " runat=" + s34 + "server" + s34 + " MaxLength=" + s34 + "40" + s34 + " Enabled=" + s34 + "false" + s34 + " TabIndex=" + s34 + "-1" + s34 + "></asp:TextBox>"+ s1310;
      v_Str_YNET += "                          </td>"+ s1310;
      v_Str_YNET += "                        </tr>"+ s1310;
      v_Str_YNET += "                        <tr>"+ s1310;
      v_Str_YNET += "                          <td colspan=" + s34 + "3" + s34 + ">"+ s1310;
      v_Str_YNET += "                            <asp:Label ID=" + s34 + "Label1" + s34 + " runat=" + s34 + "server" + s34 + " Text=" + s34 + "商品編號" + s34 + "></asp:Label>"+ s1310;
      v_Str_YNET += "                            <asp:TextBox ID=" + s34 + "tx_mtable_BDPTN" + s34 + " Width=" + s34 + "120px" + s34 + " runat=" + s34 + "server" + s34 + " MaxLength=" + s34 + "30" + s34 + "></asp:TextBox>"+ s1310;
      v_Str_YNET += "                            <asp:TextBox ID=" + s34 + "tx_bpud_BPTNA" + s34 + " Width=" + s34 + "360px" + s34 + " runat=" + s34 + "server" + s34 + " MaxLength=" + s34 + "30" + s34 + " Enabled=" + s34 + "false" + s34 + " TabIndex=" + s34 + "-1" + s34 + "></asp:TextBox>"+ s1310;
      v_Str_YNET += "                          </td>"+ s1310;
      v_Str_YNET += "                        </tr>"+ s1310;
      v_Str_YNET += "                        <tr>"+ s1310;
      v_Str_YNET += "                          <td>"+ s1310;
      v_Str_YNET += "                            <asp:Label ID=" + s34 + "lb_mtable_BDQTY" + s34 + " runat=" + s34 + "server" + s34 + " Text=" + s34 + "預付本數" + s34 + "></asp:Label>"+ s1310;
      v_Str_YNET += "                            <ig:WebNumericEditor ID=" + s34 + "tx_mtable_BDQTY" + s34 + " Width=" + s34 + "120px" + s34 + " runat=" + s34 + "server" + s34 + " MinDecimalPlaces=" + s34 + "2" + s34 + " StyleSetName=" + s34 + "Appletini" + s34 + " StyleSetPath=" + s34 + "../../../ig_res" + s34 + "></ig:WebNumericEditor>"+ s1310;
      v_Str_YNET += "                          </td>"+ s1310;
       v_Str_YNET += "                         <td>"+ s1310;
      v_Str_YNET += "                            <asp:Label ID=" + s34 + "lb_mtable_BDDE1" + s34 + " runat=" + s34 + "server" + s34 + " Text=" + s34 + "定價金額" + s34 + "></asp:Label>"+ s1310;
      v_Str_YNET += "                            <ig:WebNumericEditor ID=" + s34 + "tx_mtable_BDDE1" + s34 + " Width=" + s34 + "120px" + s34 + " runat=" + s34 + "server" + s34 + " MinDecimalPlaces=" + s34 + "2" + s34 + " StyleSetName=" + s34 + "Appletini" + s34 + " StyleSetPath=" + s34 + "../../../ig_res" + s34 + "></ig:WebNumericEditor>" + s1310;
      v_Str_YNET += "                          </td>"+ s1310;
      v_Str_YNET += "                          <td>"+ s1310;
      v_Str_YNET += "                            <asp:Label ID=" + s34 + "lb_mtable_BDRAT" + s34 + " runat=" + s34 + "server" + s34 + " Text=" + s34 + "預付％數" + s34 + "></asp:Label>"+ s1310;
      v_Str_YNET += "                            <ig:WebNumericEditor ID=" + s34 + "tx_mtable_BDRAT" + s34 + " Width=" + s34 + "120px" + s34 + " runat=" + s34 + "server" + s34 + " MinDecimalPlaces=" + s34 + "2" + s34 + " StyleSetName=" + s34 + "Appletini" + s34 + " StyleSetPath=" + s34 + "../../../ig_res" + s34 + "></ig:WebNumericEditor>"+ s1310;
      v_Str_YNET += "                          </td>"+ s1310;
      v_Str_YNET += "                        </tr>"+ s1310;
      v_Str_YNET += "                        <tr>"+ s1310;
      v_Str_YNET += "                          <td>"+ s1310;
      v_Str_YNET += "                            <asp:Label ID=" + s34 + "lb_mtable_BDTXP" + s34 + " runat=" + s34 + "server" + s34 + " Text=" + s34 + "計稅方式" + s34 + "></asp:Label>"+ s1310;
      v_Str_YNET += "                            <asp:DropDownList ID=" + s34 + "dr_mtable_BDTXP" + s34 + " Width=" + s34 + "120px" + s34 + " runat=" + s34 + "server" + s34 + " />"+ s1310;
      v_Str_YNET += "                            <asp:TextBox ID=" + s34 + "tx_mtable_BDTXP" + s34 + " Width=" + s34 + "0px" + s34 + " Visible=" + s34 + "false" + s34 + " runat=" + s34 + "server" + s34 + " />"+ s1310;
      v_Str_YNET += "                          </td>"+ s1310;
      v_Str_YNET += "                        </tr>"+ s1310;
      v_Str_YNET += "                        <tr>"+ s1310;
      v_Str_YNET += "                          <td colspan=" + s34 + "4" + s34 + ">"+ s1310;
      v_Str_YNET += "                            <asp:Label ID=" + s34 + "lb_mtable_BDRMK" + s34 + " runat=" + s34 + "server" + s34 + " Text=" + s34 + "備　　註" + s34 + "></asp:Label>"+ s1310;
      v_Str_YNET += "                            <asp:TextBox ID=" + s34 + "tx_mtable_BDRMK" + s34 + " Width=" + s34 + "500px" + s34 + " runat=" + s34 + "server" + s34 + " MaxLength=" + s34 + "100" + s34 + "></asp:TextBox>"+ s1310;
      v_Str_YNET += "                          </td>"+ s1310;
      v_Str_YNET += "                        </tr>"+ s1310;
      v_Str_YNET += "                      </table>"+ s1310;
      v_Str_YNET += "                    </asp:Panel> "+ s1310;
      v_Str_YNET += "                    <br /> "+ s1310;
      v_Str_YNET += "                           "+ s1310;
      v_Str_YNET += "                    <table>"+ s1310;
      v_Str_YNET += "                      <tr>"+ s1310;
      v_Str_YNET += "                        <td>"+ s1310;
      v_Str_YNET += "                          <igtxt:WebImageButton ID=" + s34 + "bt_New_B" + s34 + " Text=" + s34 + "新增" + s34 + " ImageDirectory=" + s34 + "../../images/" + s34 + " AutoSubmit=" + s34 + "False" + s34 + " runat=" + s34 + "server" + s34 + ">"+ s1310;
      v_Str_YNET += "                            <FocusAppearance>"+ s1310;
      v_Str_YNET += "                              <Image Url=" + s34 + "add_up.gif" + s34 + "></Image>"+ s1310;
      v_Str_YNET += "                            </FocusAppearance>"+ s1310;
      v_Str_YNET += "                            <PressedAppearance ContentShift=" + s34 + "DownRight" + s34 + ">"+ s1310;
      v_Str_YNET += "                              <Image Url=" + s34 + "add_down.gif" + s34 + "></Image>"+ s1310;
      v_Str_YNET += "                            </PressedAppearance>"+ s1310;
      v_Str_YNET += "                            <HoverAppearance ContentShift=" + s34 + "UpLeft" + s34 + ">" + s1310;
      v_Str_YNET += "                              <Image Url=" + s34 + "add_hover.gif" + s34 + "></Image>"+ s1310;
      v_Str_YNET += "                            </HoverAppearance>"+ s1310;
      v_Str_YNET += "                            <DisabledAppearance>"+ s1310;
      v_Str_YNET += "                             <Image Url=" + s34 + "add_disabled.gif" + s34 + "></Image>"+ s1310;
      v_Str_YNET += "                            </DisabledAppearance>"+ s1310;
      v_Str_YNET += "                            <Appearance>"+ s1310;
      v_Str_YNET += "                              <Image Url=" + s34 + "add_down.gif" + s34 + "></Image>"+ s1310;
      v_Str_YNET += "                            </Appearance>"+ s1310;
      v_Str_YNET += "                          </igtxt:WebImageButton>"+ s1310;
      v_Str_YNET += "                        </td>"+ s1310;
      v_Str_YNET += "                        <td>"+ s1310;
      v_Str_YNET += "                          <igtxt:WebImageButton ID=" + s34 + "bt_MOD_B" + s34 + " Text=" + s34 + "更正" + s34 + " ImageDirectory=" + s34 + "../../images/" + s34 + " runat=" + s34 + "server" + s34 + " OnClick=" + s34 + "bt_MOD_B_Click" + s34 + ">"+ s1310;
      v_Str_YNET += "                            <FocusAppearance>"+ s1310;
      v_Str_YNET += "                              <Image Url=" + s34 + "edit_up.gif" + s34 + "></Image>"+ s1310;
      v_Str_YNET += "                            </FocusAppearance>"+ s1310;
      v_Str_YNET += "                            <PressedAppearance ContentShift=" + s34 + "DownRight" + s34 + ">"+ s1310;
      v_Str_YNET += "                              <Image Url=" + s34 + "edit_down.gif" + s34 + "></Image>"+ s1310;
      v_Str_YNET += "                            </PressedAppearance>"+ s1310;
      v_Str_YNET += "                            <HoverAppearance ContentShift=" + s34 + "UpLeft" + s34 + ">"+ s1310;
      v_Str_YNET += "                              <Image Url=" + s34 + "edit_hover.gif" + s34 + "></Image>"+ s1310;
      v_Str_YNET += "                            </HoverAppearance>"+ s1310;
      v_Str_YNET += "                            <DisabledAppearance>"+ s1310;
      v_Str_YNET += "                              <Image Url=" + s34 + "edit_disabled.gif" + s34 + "></Image>"+ s1310;
      v_Str_YNET += "                            </DisabledAppearance>"+ s1310;
      v_Str_YNET += "                            <Appearance>"+ s1310;
      v_Str_YNET += "                              <Image Url=" + s34 + "edit_down.gif" + s34 + "></Image>"+ s1310;
      v_Str_YNET += "                            </Appearance>"+ s1310;
      v_Str_YNET += "                          </igtxt:WebImageButton>"+ s1310;
      v_Str_YNET += "                        </td>"+ s1310;
      v_Str_YNET += "                        <td>"+ s1310;
      v_Str_YNET += "                          <igtxt:WebImageButton ID=" + s34 + "bt_SAVE_B" + s34 + " Text=" + s34 + "存檔" + s34 + " ImageDirectory=" + s34 + "../../images/" + s34 + " runat=" + s34 + "server" + s34 + " OnClick=" + s34 + "bt_SAVE_B_Click" + s34 + ">"+ s1310;
      v_Str_YNET += "                            <FocusAppearance>"+ s1310;
      v_Str_YNET += "                              <Image Url=" + s34 + "save_up.gif" + s34 + "></Image>"+ s1310;
      v_Str_YNET += "                            </FocusAppearance>"+ s1310;
      v_Str_YNET += "                            <PressedAppearance ContentShift=" + s34 + "DownRight" + s34 + ">"+ s1310;
      v_Str_YNET += "                              <Image Url=" + s34 + "save_down.gif" + s34 + "></Image>"+ s1310;
      v_Str_YNET += "                            </PressedAppearance>"+ s1310;
      v_Str_YNET += "                            <HoverAppearance ContentShift=" + s34 + "UpLeft" + s34 + ">"+ s1310;
      v_Str_YNET += "                              <Image Url=" + s34 + "save_hover.gif" + s34 + "></Image>"+ s1310;
      v_Str_YNET += "                            </HoverAppearance>"+ s1310;
      v_Str_YNET += "                            <DisabledAppearance>"+ s1310;
      v_Str_YNET += "                              <Image Url=" + s34 + "save_disabled.gif" + s34 + "></Image>"+ s1310;
      v_Str_YNET += "                            </DisabledAppearance>"+ s1310;
      v_Str_YNET += "                            <Appearance>"+ s1310;
      v_Str_YNET += "                              <Image Url=" + s34 + "save_down.gif" + s34 + "></Image>"+ s1310;
      v_Str_YNET += "                            </Appearance>"+ s1310;
      v_Str_YNET += "                          </igtxt:WebImageButton>"+ s1310;
      v_Str_YNET += "                        </td>"+ s1310;
      v_Str_YNET += "                      </tr>"+ s1310;
      v_Str_YNET += "                    </table>"+ s1310;
      v_Str_YNET += "                    <asp:Panel ID=" + s34 + "PanEdtRightDown" + s34 + " runat=" + s34 + "server" + s34 + " Width=" + s34 + "910px" + s34 + " BorderStyle=" + s34 + "Inset" + s34 + ">"+ s1310;



      Fhdsw.Write(v_Str_YNET);
      Fhdsw.Close();
      Fhdsw.Dispose();

    }

  }
}